name: elogix_nimble
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  http: ^1.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_no_bg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  # Recommended for Android adaptive icons
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
